### ISSUE TITLE
Make spytubes placeable

### ISSUE THREAD

**Issue by Craluminum2413** [fuami/Spyglass#1]
You need to add this to attributes (better to leave translation values as 0):
```json
      "groundStorageTransform": {
        "translation": {
          "x": 0.05,
          "y": 0,
          "z": 0.024
        },
        "rotation": {
          "x": 0,
          "y": 45,
          "z": 0
        },
        "scale": 0.95
      }
```
This to behaviors
```json
{"name": "GroundStorable","properties": {"layout": "Quadrants"}}
```

**Comment by fuami** [comment]
While the transform needs adjustment thanks for the info. Will be 0.4.2

**Comment by Craluminum2413** [comment]
You forgot to add the same for `raw` spy tube, not only spy glass itself

**Comment by fuami** [comment]
I'm not particularly sure why the unmade tube would be place-able? none of the vanilla tool heads are place-able.

I realize this argument can be made about the spyglass itself, but seeing as how its an item intended to be carried a lot ease of storage IMO makes this particularly valid. So I'm fine with breaking vanilla convention since I think that placing more such tools would probobly only improve the game.

**Comment by Craluminum2413** [comment]
Maybe https://mods.vintagestory.at/pei
